// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhFX5Qv2-8wpKKsw9w6B87PfyKRmPoHPE',
    appId: '1:228700141224:web:122e38da7b89d6a21db49d',
    messagingSenderId: '228700141224',
    projectId: 'events-7400f',
    authDomain: 'events-7400f.firebaseapp.com',
    storageBucket: 'events-7400f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABLWaHKIo6wauD4fT24xzaNK_GJWLU8hc',
    appId: '1:228700141224:android:8cc7730519ab65fe1db49d',
    messagingSenderId: '228700141224',
    projectId: 'events-7400f',
    storageBucket: 'events-7400f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfb3FXu6E2kbbcqUayMCe_3_lGNQbanZ8',
    appId: '1:228700141224:ios:f92fbae7d5f206131db49d',
    messagingSenderId: '228700141224',
    projectId: 'events-7400f',
    storageBucket: 'events-7400f.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfb3FXu6E2kbbcqUayMCe_3_lGNQbanZ8',
    appId: '1:228700141224:ios:f92fbae7d5f206131db49d',
    messagingSenderId: '228700141224',
    projectId: 'events-7400f',
    storageBucket: 'events-7400f.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhFX5Qv2-8wpKKsw9w6B87PfyKRmPoHPE',
    appId: '1:228700141224:web:076a96401f7d55661db49d',
    messagingSenderId: '228700141224',
    projectId: 'events-7400f',
    authDomain: 'events-7400f.firebaseapp.com',
    storageBucket: 'events-7400f.firebasestorage.app',
  );
}
